ma1exe.beget.tech/controllers/CartController.php
<?php

namespace app\controllers;

use Yii;
use yii\helpers\Url;
use yii\web\NotFoundHttpException;
use app\models\CatalogProducts;
use app\models\CatalogCategories;
use app\models\CatalogCurrencies;
use app\models\CatalogManufacturers;
use yii\data\Pagination;

class CartController extends GlobalController
{
    public function actionIndex($category_link = false) 
    {
        $categories_query = CatalogCategories::find()->asArray()->all();
        $categories = [];
        foreach ($categories_query as $category) {
            $categories[$category['id']] = [
                'id' => $category['id'],
                'name' => $category['name'],
                'link' => $category['link']
            ];
        }

        $currencies_query = CatalogCurrencies::find()->asArray()->all();
        $currencies = [];
        foreach ($currencies_query as $currency) {
            $currencies[$currency['id']] = [
                'symbol' => $currency['symbol'],
                'rate' => $currency['rate']
            ];
        }

        $manufacturers = CatalogManufacturers::find()->asArray()->all();

        //$this->registerCssFile("/path/to/your/file/in/web/folder/style.css");
        return $this->render('index', compact('products', 'categories', 'currencies', 'manufacturers'));
    }

    public function actionCheckout() 
    {
        return $this->render('checkout');
    }

    public function actionAdditem() {
        if (Yii::$app->request->get('id')) {
            $product_id = Yii::$app->request->get('id');
            $product = CatalogProducts::findOne($product_id);
            if ($product) {
                Yii::$app->session->open();
                if (!Yii::$app->session->has('cart')) {
                    Yii::$app->session->set('cart', []);
                }
                $cart = Yii::$app->session->get('cart');
                if (isset($cart['products'][$product_id]) && intval($cart['products'][$product_id])) {
                    $cart['products'][$product_id] += 1;
                } else {
                    $cart['products'][$product_id] = 1;
                }
                Yii::$app->session->set('cart', $cart);

                return false;
            }
        }

        throw new \yii\web\NotFoundHttpException();
    }


    public function actionClearitems() {
        Yii::$app->session->open();
        if (Yii::$app->session->has('cart')) {
            $cart = Yii::$app->session->get('cart');
            if (isset($cart['products'])) {
                $cart['products'] = [];
                Yii::$app->session->set('cart', $cart);
            }
        }

        return false;
    }


    public function actionProduct($category_link = null, $product_id = null) 
    {
        $category = CatalogCategories::find()
            ->where(['link' => $category_link])
            ->one();

        if (!$category) throw new \yii\web\NotFoundHttpException();

        $product = CatalogProducts::find()
            ->where(['id' => $product_id, 'category_id' => $category['id']])
            ->one();

        if (!$product) throw new \yii\web\NotFoundHttpException();

        $currencies_query = CatalogCurrencies::find()->asArray()->all();
        $currencies = [];
        foreach ($currencies_query as $currency) {
            $currencies[$currency['id']] = [
                'symbol' => $currency['symbol'],
                'rate' => $currency['rate']
            ];
        }

        return $this->render('product', compact('product', 'category', 'currencies'));
    }
}

ma1exe.beget.tech/controllers/CatalogController.php
<?php

namespace app\controllers;

use Yii;
use yii\helpers\Url;
use yii\web\NotFoundHttpException;
use app\models\CatalogProducts;
use app\models\CatalogCategories;
use app\models\CatalogCurrencies;
use app\models\CatalogManufacturers;
use yii\data\Pagination;

class CatalogController extends GlobalController
{
    public function actionIndex($category_link = false) 
    {
        if ($category_link) {
            $current_category = CatalogCategories::find()
            ->where(['link' => $category_link])
            ->one();

            if (!$current_category) throw new \yii\web\NotFoundHttpException();

            $products_query = CatalogProducts::find()->where(['category_id' => $current_category['id']]);
            $pages = new Pagination(['totalCount' => $products_query->count()]);
            $products = $products_query->offset($pages->offset)
                ->limit($pages->limit)
                ->all();

            $popular_products = CatalogProducts::find()->where(['category_id' => $current_category['id']])->orderBy(['viewed' => SORT_DESC, 'price' => SORT_DESC])->limit(4)->all();
        } else {
            $current_category = false;

            $products_query = CatalogProducts::find();
            $pages = new Pagination(['totalCount' => $products_query->count()]);
            $products = $products_query->offset($pages->offset)
                ->limit($pages->limit)
                ->all();

            $popular_products = CatalogProducts::find()->orderBy(['viewed' => SORT_DESC, 'price' => SORT_DESC])->limit(4)->all();
        }

        /*$categories = CatalogCategories::find()->all();*/
        $manufacturers = CatalogManufacturers::find()->all();

        //$this->registerCssFile("/path/to/your/file/in/web/folder/style.css");
        return $this->render('index', compact('products', 'current_category', 'manufacturers', 'popular_products', 'pages'));
    }

    public function actionCategory($category_link = null) 
    {
        $category = CatalogCategories::find()
            ->where(['link' => $category_link])
            ->one();

        if (!$category) throw new \yii\web\NotFoundHttpException();

        $query = CatalogProducts::find()->where(['category_id' => $category['id']]);
        $pages = new Pagination(['totalCount' => $query->count()]);
        $products = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();

        $currencies_query = CatalogCurrencies::find()->asArray()->all();
        $currencies = [];
        foreach ($currencies_query as $currency) {
            $currencies[$currency['id']] = [
                'symbol' => $currency['symbol'],
                'rate' => $currency['rate']
            ];
        }

        return $this->render('category', compact('category', 'products', 'currencies', 'pages'));
    }

    public function actionProduct($category_link = null, $product_id = null) 
    {
        $category = CatalogCategories::find()
            ->where(['link' => $category_link])
            ->one();

        if (!$category) throw new \yii\web\NotFoundHttpException();

        $product = CatalogProducts::find()
            ->where(['id' => $product_id, 'category_id' => $category['id']])
            ->one();

        if (!$product) throw new \yii\web\NotFoundHttpException();

        $product->viewed++;
        $product->save();

        return $this->render('product', compact('product', 'category'));
    }
}

ma1exe.beget.tech/views/cart/checkout.php
<?php 
    use yii\helpers\Url;
    use yii\widgets\LinkPager; 

    $this->params['breadcrumbs'][] = [
        'label' => 'Корзина',
        'url' => Url::toRoute('cart/index')
    ];

    $this->title = 'Оформить заказ';
    $this->params['breadcrumbs'][] = $this->title;
?>

<div class="row">

    <div class="col-md-12">

        <div class="row">
            <div class="col-xs-12">
                <h1><?= $this->title; ?></h1>
            </div>
        </div>

        <div class="row">
            <div class="col-md-7">
                <!-- Billing Details -->
                <div class="billing-details">
                    <div class="section-title">
                        <h3 class="title">Billing address</h3>
                    </div>
                    <div class="form-group">
                        <input class="input" type="text" name="first-name" placeholder="First Name">
                    </div>
                    <div class="form-group">
                        <input class="input" type="text" name="last-name" placeholder="Last Name">
                    </div>
                    <div class="form-group">
                        <input class="input" type="email" name="email" placeholder="Email">
                    </div>
                    <div class="form-group">
                        <input class="input" type="text" name="address" placeholder="Address">
                    </div>
                    <div class="form-group">
                        <input class="input" type="text" name="city" placeholder="City">
                    </div>
                    <div class="form-group">
                        <input class="input" type="text" name="country" placeholder="Country">
                    </div>
                    <div class="form-group">
                        <input class="input" type="text" name="zip-code" placeholder="ZIP Code">
                    </div>
                    <div class="form-group">
                        <input class="input" type="tel" name="tel" placeholder="Telephone">
                    </div>
                </div>
                <!-- /Billing Details -->

                <!-- Order notes -->
                <div class="order-notes">
                    <textarea class="input" placeholder="Order Notes"></textarea>
                </div>
                <!-- /Order notes -->
            </div>

            <!-- Order Details -->
            <div class="col-md-5 order-details">
                <div class="section-title text-center">
                    <h3 class="title">Ваш заказ</h3>
                </div>
                <div class="order-summary">
                    <div class="order-col">
                        <div><strong>ТОВАР</strong></div>
                        <div><strong>СУММА</strong></div>
                    </div>
                    <div class="order-products">
                        <?php foreach ($this->context->cart_products as $cart_product): ?>
                            <div class="order-col">
                                <div><?= $cart_product['count']; ?>x <?= $cart_product['name']; ?></div>
                                <div><?= $this->context->formatPriceToRUB($cart_product['price']); ?> руб.</div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                    <div class="order-col">
                        <div>Доставка</div>
                        <div><strong>уточняется после заказа</strong></div>
                    </div>
                    <div class="order-col">
                        <div><strong>Сумма</strong></div>
                        <div><strong class="order-total">0 руб.</strong></div>
                    </div>
                </div>
                <div class="payment-method">
                    <div class="input-radio">
                        <input type="radio" name="payment" id="payment-1">
                        <label for="payment-1">
                            <span></span>
                            PayPal
                        </label>
                        <div class="caption">
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                        </div>
                    </div>
                </div>
                <div class="input-checkbox">
                    <input type="checkbox" id="terms">
                    <label for="terms">
                        <span></span>
                        I've read and accept the <a href="#">terms & conditions</a>
                    </label>
                </div>
                <a href="#" class="primary-btn order-submit">Подтвердить</a>
            </div>
            <!-- /Order Details -->
        </div>
    </div>
</div>

ma1exe.beget.tech/views/cart/index.php
<?php 
    use yii\helpers\Url;
    use yii\widgets\LinkPager; 

    $this->title = 'Корзина';
    $this->params['breadcrumbs'][] = $this->title;
?>

<div class="row">

    <div class="col-md-12">

        <div class="row">
            <div class="col-xs-12">
                <h1><?= $this->title; ?></h1>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12">
                <?php if ($this->context->cart_products): ?>
                    <?php foreach ($this->context->cart_products as $product): ?>
                        <p><?= $product['name']; ?>, <?= $product['price']; ?> x<?= $product['count']; ?></p>
                    <?php endforeach; ?>
                    <a href="<?= Url::toRoute('cart/clearitems'); ?>">Очистить корзину</a>
                    <a href="<?= Url::toRoute('cart/checkout'); ?>">Оформить заказ</a>
                <?php else: ?>
                    <p>Корзина пуста.</p>
                    <p> Вы можете <a href="<?= Url::toRoute('catalog/index'); ?>">перейти в каталог</a> или <a href="<?= Url::toRoute('site/index'); ?>">вернуться на главную</a>.</p>
                <?php endif; ?>
            </div>
        </div>

    </div>
</div>