ma1exe.beget.tech/models/CatalogProducts.php
<?php

namespace app\models;
 
use yii\db\ActiveRecord;
 
class CatalogProducts extends ActiveRecord
{


    function rules() {
        return [
            [['name', 'category_id', 'manufacturer_id', 'price', 'currency_id'], 'required'],
            ['description', 'safe']
        ];
    }


    public function attributeLabels()
    {
        return [
            'name' => 'Название',
            'sku' => 'Артикул',
            'description' => 'Описание',
            'category_id' => 'Категория',
            'manufacturer_id' => 'Производитель',
            'price' => 'Цена',
            'currency_id' => 'Валюта',
            'updated' => 'Обновлен',
            'viewed' => 'Количество просмотров',
        ];
    }


    function getCategory() {
        return $this->hasOne(CatalogCategories::className(), ['id' => 'category_id']);
    }


    function getCurrency() {
        return $this->hasOne(CatalogCurrencies::className(), ['id' => 'currency_id']);
    }


    function getManufacturer() {
        return $this->hasOne(CatalogManufacturers::className(), ['id' => 'manufacturer_id']);
    }

    
}

ma1exe.beget.tech/views/admin/products/index.php
<?php

    use yii\helpers\Url;
    use yii\widgets\LinkPager;

?>

<div class="row">
    <div class="col-xs-12">
        <h2>Товары</h2>
        <table class="table">
            <thead>
                <tr>
                    <th>Название</th>
                    <th>Артикул</th>
                    <th>Категория</th>
                    <th>Производитель</th>
                    <th>Цена</th>
                    <th>Валюта</th>
                    <th>Действия</th>
                </tr>
            </thead>
            <?php foreach ($products as $product): ?>
                <tr>
                    <td><?= $product['name']; ?></td>
                    <td><?= $product['sku']; ?></td>
                    <td><?= $product->category->name;; ?></td>
                    <td><?= $product->manufacturer->name; ?></td>
                    <td><?= $product['price']; ?></td>
                    <td><?= $product->currency->symbol; ?></td>
                    <td><a href="<?= Url::toRoute('admin/products/update/'.$product['id']); ?>">Редактировать</a></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>

<?= LinkPager::widget([
    'pagination' => $pages,
]); ?>

ma1exe.beget.tech/views/admin/products/update.php
<?php 
    use yii\widgets\ActiveForm;
    use yii\helpers\Html;
    use yii\helpers\ArrayHelper;
    use app\models\CatalogCategories;
    use app\models\CatalogManufacturers;
    use app\models\CatalogCurrencies;
?>

<?php $form = ActiveForm::begin([
    'id' => 'catalog-product',
]); ?>

    <?php if(Yii::$app->session->hasFlash('success')): ?>
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?= Yii::$app->session->getFlash('success'); ?>
        </div>
    <?php endif;?>

    <?= $form->errorSummary($model); ?>

    <?= $form->field($model, 'name'); ?>

    <?= $form->field($model, 'sku'); ?>

    <?= $form->field($model, 'description')->textarea(); ?>

    <?= $form->field($model, 'category_id')->dropDownList(ArrayHelper::map(CatalogCategories::find()->all(), 'id', 'name')) ?>

    <?= $form->field($model, 'manufacturer_id')->dropDownList(ArrayHelper::map(CatalogManufacturers::find()->all(), 'id', 'name')) ?>

    <?= $form->field($model, 'price'); ?>

    <?php if ($model->currency_id > 1): ?>

        <div class="form-group field-catalogproducts-price_rub">
            <label class="control-label" for="catalogproducts-price_rub">Цена в рублях</label>
            <input type="text" id="catalogproducts-price_rub" class="form-control" value="<?= $this->context->formatPriceToRUB($this->context->convertPriceWithRate($model->price, $model->currency->rate));  ?> руб." readonly="">

            <div class="help-block"></div>
        </div>

    <?php endif; ?>

    <?= $form->field($model, 'currency_id')->dropDownList(ArrayHelper::map(CatalogCurrencies::find()->all(), 'id', 'name')) ?>

    <?= $form->field($model, 'updated')->textInput(['readonly'=> true])?>

    <?= $form->field($model, 'viewed')->textInput(['readonly'=> true])?>

    <?= Html::submitButton('Обновить', ['class' => 'btn btn-primary']) ?>

<?php ActiveForm::end(); ?>